package velocity

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/payperplay/hosting/internal/models"
	"github.com/payperplay/hosting/pkg/logger"
)

type ConfigGenerator struct {
	configPath string
	motd       string
}

func NewConfigGenerator(configPath string, motd string) *ConfigGenerator {
	return &ConfigGenerator{
		configPath: configPath,
		motd:       motd,
	}
}

// GenerateConfig creates a velocity.toml file from the given servers
func (cg *ConfigGenerator) GenerateConfig(servers []models.MinecraftServer) error {
	// Ensure config directory exists
	if err := os.MkdirAll(filepath.Dir(cg.configPath), 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Build servers map
	serversMap := make(map[string]string)
	tryList := []string{}

	for _, server := range servers {
		if server.VelocityServerName == "" {
			continue // Skip servers not registered with Velocity
		}

		// Use host.docker.internal to reach other containers from Velocity
		address := fmt.Sprintf("host.docker.internal:%d", server.Port)
		serversMap[server.VelocityServerName] = address
		tryList = append(tryList, server.VelocityServerName)
	}

	// If no servers, add a placeholder
	if len(serversMap) == 0 {
		serversMap["lobby"] = "host.docker.internal:25566"
		tryList = append(tryList, "lobby")
	}

	// Generate the config content
	content := cg.buildConfigContent(serversMap, tryList)

	// Write to file
	if err := os.WriteFile(cg.configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	logger.Info("Generated Velocity config", map[string]interface{}{
		"path":    cg.configPath,
		"servers": len(serversMap),
	})

	return nil
}

// buildConfigContent generates the velocity.toml content
func (cg *ConfigGenerator) buildConfigContent(servers map[string]string, tryList []string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Velocity Configuration File\n")
	sb.WriteString("# Auto-generated by PayPerPlay Backend\n\n")

	// Config version
	sb.WriteString("config-version = \"2.6\"\n\n")

	// Bind address
	sb.WriteString("# What port to bind to\n")
	sb.WriteString("bind = \"0.0.0.0:25577\"\n\n")

	// MOTD
	sb.WriteString("# The MOTD to show players\n")
	sb.WriteString(fmt.Sprintf("motd = \"%s\"\n\n", cg.motd))

	// Show max players
	sb.WriteString("# Max players shown in server list\n")
	sb.WriteString("show-max-players = 100\n\n")

	// Online mode
	sb.WriteString("# Whether to enable online mode\n")
	sb.WriteString("online-mode = true\n\n")

	// Servers section
	sb.WriteString("# Backend servers\n")
	sb.WriteString("[servers]\n")
	for name, address := range servers {
		sb.WriteString(fmt.Sprintf("  %s = \"%s\"\n", name, address))
	}
	sb.WriteString("\n")

	// Try list (default servers to connect to)
	sb.WriteString("# Servers to try connecting to in order\n")
	sb.WriteString("try = [")
	for i, serverName := range tryList {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(fmt.Sprintf("\"%s\"", serverName))
	}
	sb.WriteString("]\n\n")

	// Forced hosts (for custom domains)
	sb.WriteString("# Custom domains mapped to servers\n")
	sb.WriteString("[forced-hosts]\n")
	sb.WriteString("# Example: \"survival.example.com\" = [\"survival-server\"]\n\n")

	// Advanced settings
	sb.WriteString("[advanced]\n")
	sb.WriteString("compression-threshold = 256\n")
	sb.WriteString("compression-level = -1\n")
	sb.WriteString("login-ratelimit = 3000\n\n")

	// Query settings
	sb.WriteString("[query]\n")
	sb.WriteString("enabled = true\n")
	sb.WriteString("port = 25577\n")
	sb.WriteString("show-plugins = false\n")

	return sb.String()
}

// GenerateVelocityServerName creates a unique name for Velocity
func GenerateVelocityServerName(server *models.MinecraftServer) string {
	// Format: servertype-version-id (first 8 chars)
	// Example: paper-1.20-abc12345
	serverType := strings.ToLower(string(server.ServerType))
	version := strings.ReplaceAll(server.MinecraftVersion, ".", "")
	id := server.ID
	if len(id) > 8 {
		id = id[:8]
	}

	return fmt.Sprintf("%s-%s-%s", serverType, version, id)
}
